version: '3'

services:
  server:
    image: image-server
    container_name: server
    ports:
      - "8000:8000"
    environment:
      - classifier=emberGBDT
      - labeling_service=metadefender
      - apiKeys=apikey1,apikey2,apikey3
      - load_pretrained_model=false
      - training_samples=6000
      - validation_samples=6000
      - fine_tuning=true
      - samples_for_fine_tuning=250
      - PYTHONUNBUFFERED=1

  client:
    image: image-client-poisoning
    container_name: client
    volumes:
      - "./data/goodware_samples:/app/goodware_samples"
      - "./data/malware_samples:/app/malware_samples"
    depends_on:
      - server
    environment:
      - attack=increase_false_positives
      - perc_bytes_poisoning=1
      - num_malware_files=250
      - num_goodware_files=250
      - PYTHONUNBUFFERED=1