version: '3'

services:
  server:
    image: image-server
    container_name: server
    ports:
      - "8000:8000"
    environment:
      - classifier=emberGBDT
      - labeling_service=http://labeling_service:8000/analyze
      - load_pretrained_model=false
      - training_samples=50000
      - validation_samples=20000
      - fine_tuning=true
      - continue_training=false
      - samples_for_fine_tuning=1000
      - PYTHONUNBUFFERED=1

  client:
    image: image-client-poisoning
    container_name: client
    volumes:
      - "../../data/goodware_samples:/app/goodware_samples"
      - "../../data/malware_samples:/app/malware_samples"
    depends_on:
      - server
    environment:
      - attack=increase_false_negatives
      # padding will be 50% of the original file size
      - perc_bytes_padding=0.5 
      - num_malware_files=100
      - num_goodware_files=1000
      - PYTHONUNBUFFERED=1

  labeling_service:
    image: image-server
    container_name: labeling_service
    environment:
      - classifier=malconv
      - load_pretrained_model=true
      - fine_tuning=false
      - PYTHONUNBUFFERED=1