version: '3'

services:
  server:
    image: image-server
    container_name: server
    ports:
      - "8000:8000"
    environment:
      - classifier=malconv
      - load_pretrained_model=true
      - fine_tuning=false
      - PYTHONUNBUFFERED=1

  client:
    image: image-client-evasion
    container_name: client
    volumes:
      - "./data/goodware_samples:/app/goodware_samples"
      - "./data/malware_samples:/app/malware_samples"
      - "./query/evasion-remote-classifier:/app/query"
    depends_on:
      - server
